In [1]:
print("hello")

hello

**Step 1 Data Exploration and Loading**

In [2]:
#importing dependencies

import pandas as pd

In [3]:
print(pd.__version__)

3.0.1

In [4]:

sessions = pd.read_csv("Maven+Fuzzy+Factory/website_sessions.csv", encoding_errors="ignore")
orders = pd.read_csv("Maven+Fuzzy+Factory/orders.csv", encoding_errors="ignore")
pageviews = pd.read_csv("Maven+Fuzzy+Factory/website_pageviews.csv", encoding_errors="ignore")
products = pd.read_csv("Maven+Fuzzy+Factory/products.csv", encoding_errors="ignore")
order_items = pd.read_csv("Maven+Fuzzy+Factory/order_items.csv", encoding_errors="ignore")
refunds = pd.read_csv("Maven+Fuzzy+Factory/order_item_refunds.csv", encoding_errors="ignore")

In [5]:
sessions.shape

(472871, 9)

In [6]:
sessions.head()

,website_session_id,created_at,user_id,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer
0,1,2012-03-19 08:04:16,1,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com
1,2,2012-03-19 08:16:49,2,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
2,3,2012-03-19 08:26:55,3,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
3,4,2012-03-19 08:37:33,4,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com
4,5,2012-03-19 09:00:55,5,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com

In [7]:
sessions.describe()

       website_session_id        user_id  is_repeat_session
count       472871.000000  472871.000000      472871.000000
mean        236436.000000  198037.970163           0.166119
std         136506.243908  111992.997798           0.372188
min              1.000000       1.000000           0.000000
25%         118218.500000  101966.500000           0.000000
50%         236436.000000  199483.000000           0.000000
75%         354653.500000  294433.000000           0.000000
max         472871.000000  394318.000000           1.000000

In [8]:
sessions.info()

<class 'pandas.DataFrame'>
RangeIndex: 472871 entries, 0 to 472870
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   website_session_id  472871 non-null  int64
 1   created_at          472871 non-null  str
 2   user_id             472871 non-null  int64
 3   is_repeat_session   472871 non-null  int64
 4   utm_source          389543 non-null  str
 5   utm_campaign        389543 non-null  str
 6   utm_content         389543 non-null  str
 7   device_type         472871 non-null  str
 8   http_referer        432954 non-null  str
dtypes: int64(3), str(6)
memory usage: 32.5 MB

In [9]:
sessions.duplicated().sum()

np.int64(0)

In [10]:
sessions.isnull().sum()

website_session_id        0
created_at                0
user_id                   0
is_repeat_session         0
utm_source            83328
utm_campaign          83328
utm_content           83328
device_type               0
http_referer          39917
dtype: int64

In [11]:
sessions.dropna(inplace=True)

In [12]:
sessions.isnull().sum()

website_session_id    0
created_at            0
user_id               0
is_repeat_session     0
utm_source            0
utm_campaign          0
utm_content           0
device_type           0
http_referer          0
dtype: int64

In [13]:
sessions['created_at'] = pd.to_datetime(sessions['created_at'])

In [16]:
sessions.shape

(389543, 9)

In [17]:
sessions.info()

<class 'pandas.DataFrame'>
Index: 389543 entries, 0 to 472869
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   website_session_id  389543 non-null  int64
 1   created_at          389543 non-null  datetime64[us]
 2   user_id             389543 non-null  int64
 3   is_repeat_session   389543 non-null  int64
 4   utm_source          389543 non-null  str
 5   utm_campaign        389543 non-null  str
 6   utm_content         389543 non-null  str
 7   device_type         389543 non-null  str
 8   http_referer        389543 non-null  str
dtypes: datetime64[us](1), int64(3), str(5)
memory usage: 29.7 MB

In [18]:
orders.shape

(32313, 8)

In [19]:
orders.head()

,order_id,created_at,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,20,20,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,104,104,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,147,147,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,160,160,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,177,177,1,1,49.99,19.49

In [20]:
orders.describe()

,order_id,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
count,32313.000000,32313.000000,32313.000000,32313.000000,32313.000000,32313.000000,32313.000000
mean,16157.000000,258292.288707,215691.622629,1.392474,1.238666,59.991636,22.355406
std,9328.103961,132427.649842,108402.203189,0.732277,0.426274,17.808771,6.238621
min,1.000000,20.000000,13.000000,1.000000,1.000000,29.990000,9.490000
25%,8079.000000,144828.000000,124135.000000,1.000000,1.000000,49.990000,19.490000
50%,16157.000000,263554.000000,221461.000000,1.000000,1.000000,49.990000,19.490000
75%,24235.000000,374799.000000,310542.000000,2.000000,1.000000,59.990000,22.490000
max,32313.000000,472818.000000,394273.000000,4.000000,2.000000,109.980000,41.980000

In [21]:
orders.duplicated().sum()

np.int64(0)

In [22]:
orders.isnull().sum()

order_id              0
created_at            0
website_session_id    0
user_id               0
primary_product_id    0
items_purchased       0
price_usd             0
cogs_usd              0
dtype: int64

In [23]:
orders['created_at'] = pd.to_datetime(orders['created_at'])

In [24]:
pageviews.shape

(1188124, 4)

In [25]:
pageviews.head(5)

   website_pageview_id           created_at  website_session_id pageview_url
0                    1  2012-03-19 08:04:16                   1        /home
1                    2  2012-03-19 08:16:49                   2        /home
2                    3  2012-03-19 08:26:55                   3        /home
3                    4  2012-03-19 08:37:33                   4        /home
4                    5  2012-03-19 09:00:55                   5        /home

In [26]:
pageviews.describe()

       website_pageview_id  website_session_id
count         1.188124e+06        1.188124e+06
mean          5.940625e+05        2.444585e+05
std           3.429820e+05        1.356199e+05
min           1.000000e+00        1.000000e+00
25%           2.970318e+05        1.277860e+05
50%           5.940625e+05        2.478080e+05
75%           8.910932e+05        3.627390e+05
max           1.188124e+06        4.728710e+05

In [27]:
pageviews.duplicated().sum()

np.int64(0)

In [28]:
pageviews.isnull().sum()

website_pageview_id    0
created_at             0
website_session_id     0
pageview_url           0
dtype: int64

In [29]:
pageviews['created_at'] = pd.to_datetime(pageviews['created_at'])

In [30]:
products.shape

(4, 3)

In [31]:
products.head()

   product_id           created_at                product_name
0           1  2012-03-19 08:00:00      The Original Mr. Fuzzy
1           2  2013-01-06 13:00:00       The Forever Love Bear
2           3  2013-12-12 09:00:00    The Birthday Sugar Panda
3           4  2014-02-05 10:00:00  The Hudson River Mini bear

In [32]:
products['created_at'] = pd.to_datetime(products['created_at'])

In [33]:
order_items.shape

(40025, 7)

In [34]:
order_items.head()

,order_item_id,created_at,order_id,product_id,is_primary_item,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,1,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,2,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,3,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,4,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,5,1,1,49.99,19.49

In [35]:
order_items.describe()

,order_item_id,order_id,product_id,is_primary_item,price_usd,cogs_usd
count,40025.000000,40025.000000,40025.000000,40025.000000,40025.000000,40025.000000
mean,20013.000000,17121.957502,1.770019,0.807320,48.432473,18.047976
std,11554.366599,9053.765867,1.085561,0.394408,8.012370,3.856821
min,1.000000,1.000000,1.000000,0.000000,29.990000,9.490000
25%,10007.000000,9871.000000,1.000000,1.000000,49.990000,19.490000
50%,20013.000000,17490.000000,1.000000,1.000000,49.990000,19.490000
75%,30019.000000,24818.000000,2.000000,1.000000,49.990000,19.490000
max,40025.000000,32313.000000,4.000000,1.000000,59.990000,22.490000

In [36]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 40025 entries, 0 to 40024
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_item_id    40025 non-null  int64
 1   created_at       40025 non-null  str
 2   order_id         40025 non-null  int64
 3   product_id       40025 non-null  int64
 4   is_primary_item  40025 non-null  int64
 5   price_usd        40025 non-null  float64
 6   cogs_usd         40025 non-null  float64
dtypes: float64(2), int64(4), str(1)
memory usage: 2.1 MB

In [37]:
order_items.duplicated().sum()

np.int64(0)

In [38]:
order_items['created_at'] = pd.to_datetime(order_items['created_at'])

In [39]:
refunds.shape

(1731, 5)

In [40]:
refunds.head()

,order_item_refund_id,created_at,order_item_id,order_id,refund_amount_usd
0,1,2012-04-06 11:32:43,57,57,49.99
1,2,2012-04-13 01:09:43,74,74,49.99
2,3,2012-04-15 07:03:48,71,71,49.99
3,4,2012-04-17 20:00:37,118,118,49.99
4,5,2012-04-22 20:53:49,116,116,49.99

In [41]:
refunds.describe()

       order_item_refund_id  order_item_id      order_id  refund_amount_usd
count           1731.000000    1731.000000   1731.000000        1731.000000
mean             866.000000   18472.214905  15868.242057          49.300225
std              499.840975   11438.074606   9096.061945           4.956015
min                1.000000      57.000000     57.000000          29.990000
25%              433.500000    7417.000000   7412.000000          49.990000
50%              866.000000   19858.000000  17375.000000          49.990000
75%             1298.500000   26900.000000  22539.500000          49.990000
max             1731.000000   39950.000000  32255.000000          59.990000

In [42]:
refunds.info()

<class 'pandas.DataFrame'>
RangeIndex: 1731 entries, 0 to 1730
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_item_refund_id  1731 non-null   int64
 1   created_at            1731 non-null   str
 2   order_item_id         1731 non-null   int64
 3   order_id              1731 non-null   int64
 4   refund_amount_usd     1731 non-null   float64
dtypes: float64(1), int64(3), str(1)
memory usage: 67.7 KB

In [43]:
refunds.duplicated().sum()

np.int64(0)

In [44]:
refunds['created_at'] = pd.to_datetime(refunds['created_at'])

In [45]:
sessions.to_csv("clean_sessions.csv", index=False)
orders.to_csv("clean_orders.csv", index=False)
pageviews.to_csv("clean_pageviews.csv", index=False)
products.to_csv("clean_products.csv", index=False)
order_items.to_csv("clean_order_items.csv", index=False)
refunds.to_csv("clean_refunds.csv", index=False)

In [46]:
#postgresql connection

engine_postgresql = create_engine("postgresql+psycopg2://postgres:ADMIN09876@localhost:5432/Ecommerce marketing_db")

try:
    engine_postgresql
    print("connected successfully to postgresql")
except:
    print("unable to connect")

NameError: name 'create_engine' is not defined